cchangelabs/openepd

src/openepd/bundle/writer.py
asana: [Modify Impact scope set name to alias](https://app.asana.com/0/698742722983597/1206558233457679/f)
=> feat: modify Impact scope set name to alias

src/openepd/model/specs/concrete.py
feat: add TypicalApplication spec for Concrete
=> feat: add TypicalApplication spec for Concrete

.github/workflows/run-tests.yml, src/openepd/api/test/test_common.py, src/openepd/bundle/tests/data/source/extraction-report.txt, src/openepd/bundle/tests/data/source/test-pcr.json, src/openepd/model/base.py, src/openepd/model/common.py, src/openepd/model/epd.py, src/openepd/model/factory.py, src/openepd/model/specs/README.md, src/openepd/model/specs/__init__.py, src/openepd/model/specs/base.py, src/openepd/model/specs/concrete.py, src/openepd/model/specs/steel.py, src/openepd/model/tests/__init__.py, src/openepd/model/tests/test_epd.py, src/openepd/model/tests/test_factory.py, src/openepd/model/tests/test_spec_versions.py, src/openepd/model/validation.py, src/openepd/model/validation/__init__.py, src/openepd/model/validation/common.py, src/openepd/model/validation/numbers.py, src/openepd/model/versioning.py
Add hierarchical, versioned specs. Also clean up some tests.
=> Spec-related changes

poetry.lock, pyproject.toml
fix: upgrade commitizen and make poetry version provider
=> fix: upgrade commitizen and make poetry version provider

.github/workflows/release.yml
build: update commitizen version in GH action
=> build: update commitizen version in GH action

.github/workflows/build-and-publish-wheel.yml, .github/workflows/release.yml, Makefile, poetry.toml
build: add extra step to publish package to private repository
=> build: add extra step to publish package to private repository

src/openepd/model/specs/generated/accessories.py, src/openepd/model/specs/generated/aluminium.py, src/openepd/model/specs/generated/asphalt.py, src/openepd/model/specs/generated/bulk_materials.py, src/openepd/model/specs/generated/cast_decks_and_underlayment.py, src/openepd/model/specs/generated/cladding.py, src/openepd/model/specs/generated/cmu.py, src/openepd/model/specs/generated/conveying_equipment.py, src/openepd/model/specs/generated/electrical.py, src/openepd/model/specs/generated/electrical_transmission_and_distribution_equipment.py, src/openepd/model/specs/generated/electricity.py, src/openepd/model/specs/generated/finishes.py, src/openepd/model/specs/generated/fire_and_smoke_protection.py, src/openepd/model/specs/generated/furnishings.py, src/openepd/model/specs/generated/grouting.py, src/openepd/model/specs/generated/manufacturing_inputs.py, src/openepd/model/specs/generated/masonry.py, src/openepd/model/specs/generated/material_handling.py, src/openepd/model/specs/generated/mechanical.py, src/openepd/model/specs/generated/mechanical_insulation.py, src/openepd/model/specs/generated/network_infrastructure.py, src/openepd/model/specs/generated/other_electrical_equipment.py, src/openepd/model/specs/generated/other_materials.py, src/openepd/model/specs/generated/plumbing.py, src/openepd/model/specs/generated/precast_concrete.py, src/openepd/model/specs/generated/sheathing.py, src/openepd/model/specs/generated/thermal_moisture_protection.py, src/openepd/model/specs/generated/utility_piping.py, src/openepd/model/specs/generated/wood.py, src/openepd/model/specs/generated/wood_joists.py
asana: [Add missing documentation to pydantic models](https://app.asana.com/0/698742722983597/1206887306120203/f)
=> fix: add descriptions to all specs

src/openepd/model/specs/generated/precast_concrete.py
asana: [Updates to precast category](https://app.asana.com/0/698742722983597/1207326942987195/f)
=> feat(specs): upgrade PrecastConcrete category properties

src/openepd/model/specs/generated/conveying_equipment.py
asana: [[OpenEpd] Resolve typo with vertical_rize -> vertical_rise](https://app.asana.com/0/698742722983597/1207493875153217/f)
=> fix(specs): resolve typo in `vertical_rize` -> `vertical_rise`

src/openepd/model/org.py, src/openepd/model/pcr.py
=> feat: add declared_units field for PCR

src/openepd/model/lcia.py
https://lca-forum.org/english/news/index.html#lime2
=> feat: add LIME2 LCIA method to supported methods

src/openepd/model/base.py, src/openepd/model/epd.py, src/openepd/model/factory.py, src/openepd/model/generic_estimate.py, src/openepd/model/tests/test_factory.py
asana: [List and Get endpoints for Generic Estimates in openEPD](https://app.asana.com/0/1207618459878072/1207739177346287/f)
=> feat: add GenericEstimate object to openEPD

src/openepd/model/geography.py, tools/openepd/codegen/generate_geography_enum.py
It makes sense - and it is used in EC3.
=> fix: improve ordering of geography enum (description changed)

src/openepd/model/base.py, src/openepd/model/epd.py, src/openepd/model/generic_estimate.py
They were previously updated to OrgRef which broke existing contract.
=> fix: restore correct Org entities in EPD, GenericEstimate

src/openepd/model/specs/generated/enums.py, src/openepd/model/specs/generated/mechanical.py
asana: [[OpenEPD] Add new spec](https://app.asana.com/0/698742722983597/1207610993884634/f)
=> feat(specs): add HvacDuctsV1 specification

src/openepd/model/specs/generated/electrical.py, src/openepd/model/specs/generated/network_infrastructure.py
asana: [Create conduit categories](https://app.asana.com/0/1207794058953829/1207725964144739/f)
=> feat(specs): add Conduit categories

src/openepd/api/test/test_common.py, src/openepd/model/specs/generated/finishes.py
asana: [Improve Painting/Coating to reduce confusion](https://app.asana.com/0/1207794058953829/1205958769714263/f)
=> feat(specs): add Painting subcategories

src/openepd/model/specs/generated/steel.py
asana: [Update description for Steel/tensile strength/openepd](https://app.asana.com/0/1203527467850668/1207816216791523/f)
=> fix: correct description for Steel.yield_tensile_str

src/openepd/model/specs/generated/electrical.py, src/openepd/model/specs/generated/enums.py, src/openepd/model/specs/generated/mixins/__init__.py, src/openepd/model/specs/generated/mixins/conduit_mixin.py, src/openepd/model/specs/generated/network_infrastructure.py
asana: [[OpenEpd] Add conduit properties](https://app.asana.com/0/1207501793930589/1207868902793418/f)
=> feat(specs): add Conduit category properties

README.md, src/openepd/api/average_dataset/__init__.py, src/openepd/api/average_dataset/generic_estimate_sync_api.py, src/openepd/api/average_dataset/industry_epd_sync_api.py, src/openepd/api/common.py, src/openepd/api/sync_client.py, src/openepd/api/test/test_sync_api_client.py, src/openepd/model/generic_estimate.py, src/openepd/model/geography.py, src/openepd/model/industry_epd.py
This is only GEs, please use it, will add IEPDs tomorrow.
=> Add IEPD and GE API clients

src/openepd/model/declaration.py, src/openepd/model/epd.py
fix: generalize `version` field from EPD
=> fix: generalize `version` field from EPD

src/openepd/model/declaration.py, src/openepd/model/validation/quantity.py
As it is a stored carbon, it should be a GWP, not just any mass.
=> fix: add correct kg_C_per_declared_unit to be AmountGWP

src/openepd/model/common.py, src/openepd/model/lcia.py, src/openepd/model/specs/base.py, src/openepd/model/validation/quantity.py
asana: [Add all impact definitions from OpenEPD spreadsheet to spec](https://app.asana.com/0/1203527467850668/1208021404558576/f)
=> feat: add validation to scopesets and allow unknown ones

src/openepd/api/average_dataset/generic_estimate_sync_api.py, src/openepd/api/epd/sync_api.py
DO NOT RELEASE IT BEFORE CHE's REFACTORING
=> Remove exclude_defaults parameter

src/openepd/bundle/model.py
asana: [Add created_date into openEPDBundle manifest](https://app.asana.com/0/1203445770194826/1208517598305141/f)
=> feat(bundle): add created_date into openEPDBundle manifest

src/openepd/model/standard.py
asana: [Migrate Standards endpoints](https://app.asana.com/0/1203527467850668/1208449709553199/f)
=> refactor: migrate openepd/standards to Pydantic

src/openepd/model/org.py
asana: [Refactor openEPD to use pydantic objects](https://app.asana.com/0/1203527467850668/1207500417639446/f)
=> feat: add location-specific properties to Plant

src/openepd/model/epd.py
asana: [Refactor openEPD to use pydantic objects](https://app.asana.com/0/1203527467850668/1207500417639446/f)
=> fix: add explicit format_version for EpdPreview

src/openepd/model/industry_epd.py
asana: [Add Sample Size to openIndustry EPD](https://app.asana.com/0/1203527467850668/1208019896837198/f)
=> feat: add sample_size to industry epd

src/openepd/model/org.py
asana: [openEPD Plants API: finish moving to pydantic](https://app.asana.com/0/1203527467850668/1208790169885241/f)
=> feat: extract PlantRef from Plant model

src/openepd/model/common.py
The schema should contain the 'well-known' keys as well as arbitrary keys.
asana: [openEPD apidocs/attachments: specify wellknown types](https://app.asana.com/0/1203527467850668/1208716653411594/f)
=> fix: correct the schema for attachments object

src/openepd/model/specs/range/furnishings.py, src/openepd/model/specs/singular/furnishings.py
asana: [[OpenEPD] add new specification](https://app.asana.com/0/1205308458277257/1209338470822045)
=> feat(specs): update `Furnishings` subcategories

src/openepd/model/specs/enums.py, src/openepd/model/specs/range/finishes.py, src/openepd/model/specs/singular/finishes.py
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1210252537393829
=> feat(specs): allow additional CementBoard thicknesses

src/openepd/model/org.py
asana: [[openEPD] Add 'company_description' text field to Org](https://app.asana.com/1/654700433662128/project/666075018299960/task/1210597444825822?focus=true)
=> feat: add company description field to organization model

poetry.lock, src/openepd/model/base.py, src/openepd/model/lcia.py, src/openepd/model/org.py, src/openepd/model/tests/test_epd.py, src/openepd/model/tests/test_schema_gen.py, src/openepd/model/versioning.py
This PR should solve issues related to OpenAPI schema generation on pydantic 2+ raised by @aduverger in [PR 155](https://github.com/cchangelabs/openepd/pull/155).
=> Schema generation improvements

src/openepd/model/lcia.py
asana: [[openEPD] Add LCIA method "GWP-GHG"](https://app.asana.com/1/654700433662128/project/1205308458277257/task/1210865054410207?focus=true)
=> feat: add GWP-GHG LCIA method

pyproject.toml, src/openepd/model/declaration.py
asana: [Add Third Party Verifier name](https://app.asana.com/1/654700433662128/project/666075018299960/task/1210605074248467?focus=true)
=> feat: add third party verifier name field to declaration model (v6)

pyproject.toml, src/openepd/model/declaration.py
asana: [Add Third Party Verifier name](https://app.asana.com/1/654700433662128/project/666075018299960/task/1210605074248467?focus=true)
=> feat: add third party verifier name field to declaration model (v7)

src/openepd/model/common.py, src/openepd/model/org.py, src/openepd/model/tests/test_org.py
asana: [Implement support for org.logo in openEPD](https://app.asana.com/1/654700433662128/project/1205308458277257/task/1211068518169976?focus=true)
=> feat: implement `Org.logo` field

src/openepd/model/declaration.py, src/openepd/model/tests/test_epd.py
asana: [[Open EPD] Implement simple data urls support for product_picture](https://app.asana.com/1/654700433662128/project/1205308458277257/task/1211258148363972?focus=true)
=> feat: add dataUrl support for product image fields (v7)
